# -*- coding: utf-8 -*-
"""Veri_Bilimine_Giriş_1.hafta_odev.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KahJ6pejcbiMvyEPQdf8oi63EnrCXD0W
"""

ad = input("Adınızı giriniz: ")
yas = int(input("Yaşınızı giriniz: "))
boy = float(input("Boyunuzu (metre cinsinden, örn: 1.75) giriniz: "))
print(f"Hoş geldiniz {ad}! Yaşınız: {yas}, Boyunuz: {boy}m.")

matematik_notu = 85
fizik_notu = 70
kimya_notu = 90
ortalama = (matematik_notu + fizik_notu + kimya_notu) / 3
print(f"Derslerinizin not ortalaması: {ortalama}")

metin = "Merhaba Python"
ilk_karakter = metin[0]
son_karakter = metin[-1]
uzunluk = len(metin)
ters_metin = metin[::-1]

print(f"Orijinal Metin: '{metin}'")
print(f"İlk Karakter: {ilk_karakter}")
print(f"Son Karakter: {son_karakter}")
print(f"Uzunluk: {uzunluk}")
print(f"Ters Hali: '{ters_metin}'")

sayi1 = float(input("Birinci sayıyı giriniz: "))
sayi2 = float(input("İkinci sayıyı giriniz: "))

toplama = sayi1 + sayi2
cikarma = sayi1 - sayi2
carpma = sayi1 * sayi2
bolme = sayi1 / sayi2
mod_alma = sayi1 % sayi2  # Birinci sayının ikinci sayıya bölümünden kalan

print(f"{sayi1} + {sayi2} = {toplama}")
print(f"{sayi1} - {sayi2} = {cikarma}")
print(f"{sayi1} * {sayi2} = {carpma}")
print(f"{sayi1} / {sayi2} = {bolme}")
print(f"{sayi1} % {sayi2} = {mod_alma}")

ogrenci_ortalamasi = float(input("Öğrencinin not ortalamasını giriniz: "))
if ogrenci_ortalamasi > 50:
    print("Sonuç: Geçti")
else:
    print("Sonuç: Kaldı")

kullanici_yasi = int(input("Yaşınızı giriniz: "))

if kullanici_yasi > 18:
    print("Ehliyet alabilirsiniz.")
else:
    print("Ehliyet alamazsınız.")

urun_fiyati = float(input("Ürünün fiyatını giriniz: "))
indirim_orani = float(input("İndirim oranını (%) giriniz: "))

indirim_miktari = urun_fiyati * (indirim_orani / 100)
indirimli_fiyat = urun_fiyati - indirim_miktari

print(f"Ürünün indirimli yeni fiyatı: {indirimli_fiyat} TL")

a = True
b = False

print(f"a and b: {a and b}")  # and: Her ikisi de True ise True döner.
print(f"a or b: {a or b}")    # or: En az biri True ise True döner.
print(f"not a: {not a}")      # not: Değerin tersini alır (True ise False, False ise True).
print(f"not b: {not b}")

fiyat1 = float(input("1. ürünün fiyatını giriniz: "))
fiyat2 = float(input("2. ürünün fiyatını giriniz: "))
fiyat3 = float(input("3. ürünün fiyatını giriniz: "))

toplam_fiyat = fiyat1 + fiyat2 + fiyat3
print(f"Sepetinizin indirimsiz toplam tutarı: {toplam_fiyat} TL")

if toplam_fiyat > 200:
    print("Toplam tutar 200 TL'yi geçtiği için %10 indirim uygulanmıştır.")
    son_fiyat = toplam_fiyat * 0.90
else:
    son_fiyat = toplam_fiyat

print(f"Ödenecek nihai tutar: {son_fiyat} TL")

guncel_yil = 2025
dogum_yili = int(input("Doğum yılınızı giriniz: "))

yas_hesabi = guncel_yil - dogum_yili

print(f"Hesaplanan yaşınız: {yas_hesabi}")

if 0 <= yas_hesabi <= 12:
    print("Siz bir 'Çocuksunuz'.")
elif 13 <= yas_hesabi <= 17:
    print("Siz bir 'Ergensiniz'.")
else: # 18 ve üzeri tüm durumlar
    print("Siz bir 'Yetişkinsiniz'.")

